name: Release on tag

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, test, Publish
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
          always-auth: 'true'
      - run: yarn install --frozen-lockfile
        env:
          CI: true
      - name: Read npm token from env
        run: |
          ([[ ! -z ${{ secrets.NPM_TOKEN }} ]] && npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}) || echo "Did not write npm token"
          cp $NPM_CONFIG_USERCONFIG  ~/.npmrc
          cat ~/.npmrc
      - name: Potentially publish canary to npm
        run: |
          if \
            ls ~/.npmrc >/dev/null 2>&1 && \
            [[ $(git describe --exact-match 2> /dev/null || :) =~ -canary ]]; \
          then
            yarn run lerna publish from-git --no-verify-access --npm-tag canary --yes
          else
            echo "Did not publish canary"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Potentially publish stable to npm
        run: |
          if \
            ls ~/.npmrc >/dev/null 2>&1 && \
            [[ ! $(git describe --exact-match 2> /dev/null || :) =~ -canary ]]; \
          then
            yarn run lerna publish from-git --no-verify-access --yes
          else
            echo "Did not publish"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
